
postgresql: &postgresql
  adapter: postgresql
  host: localhost
  pool: 5
  timeout: 5000
  username: test
  password: test

development:
  
  <<: *postgresql
  database: lifestyle_development

test:
  <<: *postgresql
  database: lifestyle_test

production:
  <<: *postgresql
  database: lifestyle_production
